version: "3"
services:
  flask:
    build:
      dockerfile: Dockerfile
      context: ../
    volumes:
      - ../:/app
    environment:
      FLASK_ENV: development
    ports:
      - "5000:80"


#  testing:
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ../../UCTesting
#    ports:
#      - '5000:5000'
