version: "3"
services:
  flask:
    build:
      dockerfile: Dockerfile
      context: ../
    ports:
      - "5000:5000"


#  testing:
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ../../UCTesting
#    ports:
#      - '5000:5000'
